version: '3'

services:

  mongos:
    container_name: mongos
    image: mongo
    command: mongos --configdb cfgrs/configs1:27017 --bind_ip 0.0.0.0 --port 27017
    ports:
      - "30000:27017"
    networks:
      - config_net-mongodb

networks:
  config_net-mongodb:
    external: true

