version: '3'

services:

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongos
    networks:
      - config_net-mongodb

volumes:
  app-volume:

networks:
  config_net-mongodb:
    external: true