version: "3.8"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - app-volume:/code/dataset
  db:
    image: postgres:alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: relational-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - app-volume:/code/dataset
volumes:
  app-volume:
